apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: camunda8-dev
  labels:
    app: camunda8-process-demo
  name: camunda8-process-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda8-process-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: camunda8-process-demo
    spec:
      containers:
      - image: camunda8-process-demo:0.0.2-SNAPSHOT
        name: camunda8-process-demo
        imagePullPolicy: Never
        resources: {}
        env:
          - name: ZEEBE_CLIENT_BROKER_GATEWAYADDRESS
            value: camunda-zeebe-gateway:26500

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: camunda8-process-demo
  type: ClusterIP
status:
  loadBalancer: {}
