camunda:
  client:
    mode: self-managed
    tenant-ids:
      - <default>
    auth:
      client-id: zeebe
      client-secret: 3hjeaxrh5i
      issuer: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      prefer-rest-over-grpc: false
      audience: zeebe-api
      scope: # optional 