apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
spec:
  selector:
    app: camunda-8-example-customer-onboarding
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
